AUTHORIZATION_TOKEN: sk_7cd9405de7bb48f5ab36b004038eb1a3

UPLOAD_STOCK_DATA: 5
SHOW_DATA: 5
UPLOAD_COMPANY: 360000

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:2022/postgres
    username: postgres
    password: superuser
  jpa:
    hibernate:
      ddl-auto: update